---
version: "2.1"
services:
  openssh-server:
    build: .
    hostname: openssh-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
      - SUDO_ACCESS=false
      # - PASSWORD_ACCESS=true
      # - USER_PASSWORD=password1234
      - PASSWORD_ACCESS=false
      - USER_NAME=linuxserver.io
    volumes:
      - $PWD/repos:/repos
      - $PWD/config:/config
    ports:
      - 2222:2222
    restart: unless-stopped